## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [5]:
# LinearRegression
boston = datasets.load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)
regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)
regr.coef_

array([-1.15966452e-01,  4.71249231e-02,  8.25980146e-03,  3.23404531e+00,
       -1.66865890e+01,  3.88410651e+00, -1.08974442e-02, -1.54129540e+00,
        2.93208309e-01, -1.34059383e-02, -9.06296429e-01,  8.80823439e-03,
       -4.57723846e-01])

In [6]:
mean_squared_error(y_test, y_pred)

25.41958712682187

In [11]:
# Lasso
boston = datasets.load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)
regr = linear_model.Lasso(alpha=0.5)
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)
regr.coef_

array([-0.08860117,  0.04829133, -0.01107435,  0.        , -0.        ,
        2.66101769, -0.00307949, -0.98440282,  0.25664031, -0.01593271,
       -0.73252329,  0.00884426, -0.59210164])

In [12]:
mean_squared_error(y_test, y_pred)

26.94483860388666

In [13]:
# Ridge
boston = datasets.load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)
regr = linear_model.Ridge(alpha=0.5)
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)
regr.coef_

array([-1.13720313e-01,  4.76370805e-02, -1.25294762e-02,  3.07531514e+00,
       -1.19789169e+01,  3.91845004e+00, -1.51046851e-02, -1.47224633e+00,
        2.81475089e-01, -1.37075697e-02, -8.57737917e-01,  9.03172343e-03,
       -4.62924119e-01])

In [14]:
mean_squared_error(y_test, y_pred)

25.598133627552848